Update mern.yml

diff --git a/.github/workflows/mern.yml b/.github/workflows/mern.yml
--- a/.github/workflows/mern.yml
+++ b/.github/workflows/mern.yml
@@ -41,7 +41,11 @@ jobs:
         run: echo "USERNAME is $USERNAME"
 
       - name: Add server to known hosts
-        run: ssh-keyscan -H "$LOCAL_IP" >> ~/.ssh/known_hosts
+        run: |
+         if ! ssh-keyscan -H "$LOCAL_IP" >> ~/.ssh/known_hosts 2>/dev/null; then
+         echo "Failed to add $LOCAL_IP to known_hosts"
+         exit 1
+         fi
         
 
       - name: Test SSH connection
